version: "3"
services:
  users-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_PASSWORD=43320
    expose:
      - 8080
    ports:
      - "8080:8080"